// Render checked-in TeX as self-contained SVG; no GitHub client MathJax required.
const fs = require('node:fs');
const path = require('node:path');
const {mathjax} = require('mathjax-full/js/mathjax.js');
const {TeX} = require('mathjax-full/js/input/tex.js');
const {SVG} = require('mathjax-full/js/output/svg.js');
const {liteAdaptor} = require('mathjax-full/js/adaptors/liteAdaptor.js');
const {RegisterHTMLHandler} = require('mathjax-full/js/handlers/html.js');
require('mathjax-full/js/input/tex/ams/AmsConfiguration.js');
const adaptor = liteAdaptor();
RegisterHTMLHandler(adaptor);
const document = mathjax.document('', {InputJax: new TeX({packages: ['base', 'ams']}), OutputJax: new SVG({fontCache: 'none'})});
const directory = path.resolve(__dirname, '../../assets/math');
for (const id of ['reasoning-loop', 'world-interface']) {
  const tex = fs.readFileSync(path.join(directory, id + '.tex'), 'utf8').trim();
  const rendered = adaptor.outerHTML(document.convert(tex, {display: true}));
  if (/data-mjx-error|<merror/.test(rendered)) throw new Error('Invalid TeX: ' + id);
  let svg = rendered.match(/<svg\b[\s\S]*<\/svg>/)[0];
  const box = svg.match(/viewBox="([^"]+)"/)[1].split(/\s+/).map(Number);
  const padding = 650;
  const [x, y, w, h] = [box[0] - padding, box[1] - padding, box[2] + 2 * padding, box[3] + 2 * padding];
  const width = Math.ceil(w / 50), height = Math.ceil(h / 50);
  svg = svg.replace(/viewBox="[^"]+"/, `viewBox="${x} ${y} ${w} ${h}"`)
    .replace(/width="[^"]+"/, `width="${width}"`).replace(/height="[^"]+"/, `height="${height}"`)
    .replace(/currentColor/g, '#24292f')
    .replace(/(<svg\b[^>]*>)/, `$1<title>${id.replaceAll('-', ' ')}</title><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="250" fill="#ffffff"/>`);
  const content = '<!-- Generated by tools/math/render.cjs from ' + id + '.tex. -->\n' + svg + '\n';
  const target = path.join(directory, id + '.svg');
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(target, 'utf8') !== content) throw new Error('Stale formula SVG: ' + id);
  } else fs.writeFileSync(target, content);
}
console.log('Formula SVGs validated against their TeX sources.');
